# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Flixte' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Flixte
  pod 'GoogleSignIn', '~> 4.4.0'

  target 'Flixte-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'FlixteTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

#target 'Flixte-tvOS' do
#  # Comment the next line if you don't want to use dynamic frameworks
#  use_frameworks!
#
#  # Pods for Flixte-tvOS
#
#  target 'Flixte-tvOSTests' do
#    inherit! :search_paths
#    # Pods for testing
#  end
#
#end
